### ISSUE TITLE
Distance matrix calculation potential speed ups.

### ISSUE THREAD

**Issue by xydinesh** [valhalla/valhalla#973]
I'm running Valhalla in m4.4xlarge with colorado.osm.pbf from geofabric. For random points generated around Denver area distance matrix run time as follows. I'm using sources_to_targets option to calculate distance matrix with 50x50 chunk size.

```
root@ip-10-11-0-61:/opt/user_data/distance-benchmark# fab run:name=valhalla,location=denver,repeat=1,chunk_width=50,chunk_length=50

valhalla:denver city 10x10 -> 0.376 sec
valhalla:denver city 20x20 -> 0.776 sec
valhalla:denver city 50x50 -> 2.205 sec
valhalla:denver city 100x100 -> 3.121 sec
valhalla:denver city 200x200 -> 6.633 sec
valhalla:denver city 300x300 -> 13.935 sec
valhalla:denver city 500x500 -> 34.475 sec
valhalla:denver city 1000x1000 -> 111.297 sec
```

The distance matrix run time is slower compare to OSRM. I'm not sure if I'm missing anything on configuration. I ran valhalla_route_service with 16 threads.

```
valhalla_route_service valhalla.json 16
```

OSRM run time for similar distance matrix calculation as follows,

|matrix_size | denver|
| ---------- | ------- |
|10  | 0.01009821892|
|20  | 0.01778244972|
|50  | 0.03152441978|
|100  | 0.2796823978|
|200  | 0.9147963524|
|300  | 1.972381353|
|500  | 5.995920181|
|1000  | 31.28058243|

I would like to try if you have any suggestions to speed up distance matrix calculations.  Thanks !

**Comment by dnesbitt61** [comment]
Are these auto, pedestrian, bicycle? For extremely large one to many we could use the isochrone logic to compute a time array and then sample that array at each location. For many to many I can't think of any speedups. Since we use custom, run-time costing rather than pre-baked costs I wouldn't think we would be as fast as OSRM.

**Comment by xydinesh** [comment]
These run times are for auto. Thanks for your response.

**Comment by xydinesh** [comment]
I was experimenting with this further, I got some speedup (2x) from increasing chunk size from 50x50 to 100x100. However valhalla_route_service does not seem to free memory when serving requests. It grew up to ~80GB of RAM usage. I don't think that is expected behavior. Is there anything I can tune in configuration file ?

**Comment by dnesbitt61** [comment]
Another thought is to try multi-threading the CostMatrix code and perhaps the loki edge search code. For server implementations we have not used any multi-threading and are assuming being able to handle multiple simultaneous requests is where we get concurrency. But for single requests in an application we may be able to improve performance with multiple threads. Not sure when we might get to testing this, but it could be worthwhile for some users.

**Comment by dnesbitt61** [comment]
As for memory use - each location (from and to) will have its own priority queue and edge label data. Presumably these are sized appropriate to the problem (how far locations are away from each other) but it could be that further optimization of memory use is required. We have seen high memory use (hence the limit of 50x5). Are you saying that memory is not cleared so that subsequent requests exhaust memory or just that memory use overall is high?

**Comment by wdav** [comment]
Memory is not cleared consistently, and subsequent requests can exhaust memory causing a crash. 

An example for a similar many-to-many with 1000*1000 locations I ran is that it also took upwards of 80GB and the memory is not freed.  Even on small sets of data the memory is not freed between requests.  

Consequently, this was not an issue with versions sometime previous to June/July 2017, I have not verified the change, but it appears that most of the memory is being consumed by something related to DoubleBucketQueues. 

With an older revision from back in June (via Docker valhalla-source-1.2.0 image) I am able to generate a 1000*1000 many-to-many matrix of locations with < 2GB memory consumed and it takes approximately 6 minutes.

**Comment by dnesbitt61** [comment]
We can look later, but I do see Clear called at the start of CostMatrix::SourceToTarget. This method should call the DoubleBucketQueue destructor which calls the clear method to delete all the temp data in the buckets

**Comment by wdav** [comment]
I agree with your assessment, and that's where my research had to stop at the time. I am interested to help as needed, it'd be great to solve this.

**Comment by xydinesh** [comment]
Please update this issue when you get a chance to work on this. I can help to test. Thanks !

**Comment by dnesbitt61** [comment]
I have not been able to reproduce this - do you have an example URL? I put a print statement in the DoubleBucketQueue constructor and the clear method. A sample I did has equal numbers printed - so it seems that the buckets are cleared. This is called when CostMatrix goes out of scope. I ran the same URL many times and did not see any memory growth.

**Comment by xydinesh** [comment]
I was computing 1000x1000 matrix using 100x100 chunks. 100 requests of 100x100 hit the server asynchronously.  With a single thread it grew over 4GB. Not sure, if single request can reproduce it. If you can stand up a server, may be I can try to hit with the same requests.

**Comment by wdav** [comment]
Here's an example of ~5GB of memory not being released with valhalla/docker:source-1.3.4 after receiving a single many-to-many request of 120 locations:

```
// Idle system
$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:40:55 UTC 2017
KiB Mem : 53588628 total, 50165056 free,   352292 used,  3071280 buff/cache

// Valhalla starts
root@3ef24466f0b8:/# valhalla_route_service /conf/valhalla.json 
2017/10/24 20:40:58.316425 [WARN] Tile extract could not be loaded

// Memory after Valhalla starts
$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:41:01 UTC 2017
KiB Mem : 53588628 total, 50107752 free,   409292 used,  3071584 buff/cache

// Valhalla Request 0 received and processed
0 2017/10/24 20:41:07.130175 GET /many_to_many?json={%22locations%22:[{%22lat%22:35.846761,%22lon%22:-78.743134},{%22lat%22:35.882374,%22lon%22:
-78.594818},{%22lat%22:35.832288,%22lon%22:-78.471222},{%22lat%22:35.765458,%22lon%22:-78.493195},{%22lat%22:35.668454,%22lon%22:-78.464355},{%2
2lat%22:35.680725,%22lon%22:-78.715668},{%22lat%22:35.779943,%22lon%22:-78.636017},{%22lat%22:35.827835,%22lon%22:-78.574219},{%22lat%22:35.9457
71,%22lon%22:-78.664856},{%22lat%22:35.914635,%22lon%22:-78.778839},{%22lat%22:35.837855,%22lon%22:-78.848877},{%22lat%22:35.75097,%22lon%22:-78
.929901},{%22lat%22:35.681841,%22lon%22:-78.809052},{%22lat%22:35.533344,%22lon%22:-78.799438},{%22lat%22:35.495338,%22lon%22:-78.339386},{%22la
t%22:35.710838,%22lon%22:-77.908173},{%22lat%22:35.778828,%22lon%22:-78.10318},{%22lat%22:35.840082,%22lon%22:-78.30368},{%22lat%22:35.69411,%22
lon%22:-78.559113},{%22lat%22:35.629396,%22lon%22:-78.539886},{%22lat%22:35.797766,%22lon%22:-78.776093},{%22lat%22:35.810018,%22lon%22:-78.7966
92},{%22lat%22:35.769915,%22lon%22:-78.844757},{%22lat%22:35.899063,%22lon%22:-78.943634},{%22lat%22:35.95133,%22lon%22:-78.892822},{%22lat%22:3
5.943548,%22lon%22:-78.984833},{%22lat%22:36.024668,%22lon%22:-78.990326},{%22lat%22:35.998008,%22lon%22:-78.888702},{%22lat%22:36.024668,%22lon
%22:-78.818665},{%22lat%22:36.015782,%22lon%22:-78.810425},{%22lat%22:35.955777,%22lon%22:-78.734894},{%22lat%22:36.05132,%22lon%22:-78.730774},
{%22lat%22:35.863457,%22lon%22:-78.670349},{%22lat%22:35.910186,%22lon%22:-78.721161},{%22lat%22:35.943548,%22lon%22:-78.688202},{%22lat%22:35.9
49106,%22lon%22:-78.596191},{%22lat%22:35.933541,%22lon%22:-78.618164},{%22lat%22:35.896838,%22lon%22:-78.63327},{%22lat%22:35.825608,%22lon%22:
-78.630524},{%22lat%22:35.766572,%22lon%22:-78.689575},{%22lat%22:35.729792,%22lon%22:-78.75},{%22lat%22:35.588085,%22lon%22:-78.760986},{%22lat
%22:35.670685,%22lon%22:-78.891449},{%22lat%22:35.678494,%22lon%22:-78.987579},{%22lat%22:35.785513,%22lon%22:-78.984833},{%22lat%22:35.847874,%
22lon%22:-79.027405},{%22lat%22:35.887937,%22lon%22:-79.001312},{%22lat%22:35.919084,%22lon%22:-79.045258},{%22lat%22:35.95133,%22lon%22:-79.023
285},{%22lat%22:35.994674,%22lon%22:-78.97522},{%22lat%22:35.917972,%22lon%22:-78.906555},{%22lat%22:35.95133,%22lon%22:-78.940887},{%22lat%22:3
6.046878,%22lon%22:-78.940887},{%22lat%22:36.086841,%22lon%22:-78.903809},{%22lat%22:36.042437,%22lon%22:-78.887329},{%22lat%22:35.961335,%22lon
%22:-78.831024},{%22lat%22:35.992452,%22lon%22:-78.844757},{%22lat%22:36.057981,%22lon%22:-78.848877},{%22lat%22:35.999119,%22lon%22:-78.780212}
,{%22lat%22:35.968004,%22lon%22:-78.802185},{%22lat%22:35.953553,%22lon%22:-78.767853},{%22lat%22:35.92242,%22lon%22:-78.837891},{%22lat%22:35.8
86825,%22lon%22:-78.813171},{%22lat%22:35.86457,%22lon%22:-78.829651},{%22lat%22:35.870134,%22lon%22:-78.769226},{%22lat%22:35.87236,%22lon%22:-
78.712921},{%22lat%22:35.834515,%22lon%22:-78.704681},{%22lat%22:35.826721,%22lon%22:-78.681335},{%22lat%22:35.80779,%22lon%22:-78.664856},{%22l
at%22:35.806677,%22lon%22:-78.728027},{%22lat%22:35.779943,%22lon%22:-78.740387},{%22lat%22:35.757657,%22lon%22:-78.715668},{%22lat%22:35.753199
,%22lon%22:-78.660736},{%22lat%22:35.8501,%22lon%22:-78.614044},{%22lat%22:35.797766,%22lon%22:-78.603058},{%22lat%22:35.756543,%22lon%22:-78.60
4431},{%22lat%22:35.719758,%22lon%22:-78.63327},{%22lat%22:35.718643,%22lon%22:-78.697815},{%22lat%22:35.806677,%22lon%22:-78.844757},{%22lat%22
:35.827835,%22lon%22:-78.815918},{%22lat%22:35.782171,%22lon%22:-78.817291},{%22lat%22:35.748741,%22lon%22:-78.799438},{%22lat%22:35.734251,%22l
on%22:-78.837891},{%22lat%22:35.755428,%22lon%22:-78.879089},{%22lat%22:35.793311,%22lon%22:-78.883209},{%22lat%22:35.831175,%22lon%22:-78.87908
9},{%22lat%22:35.859005,%22lon%22:-78.879089},{%22lat%22:35.895725,%22lon%22:-78.868103},{%22lat%22:35.827835,%22lon%22:-78.912048},{%22lat%22:3
5.772143,%22lon%22:-78.916168},{%22lat%22:35.737595,%22lon%22:-78.895569},{%22lat%22:35.719758,%22lon%22:-78.859863},{%22lat%22:35.720873,%22lon
%22:-78.788452},{%22lat%22:35.696341,%22lon%22:-78.773346},{%22lat%22:35.711953,%22lon%22:-78.728027},{%22lat%22:35.697456,%22lon%22:-78.670349}
,{%22lat%22:35.691879,%22lon%22:-78.608551},{%22lat%22:35.726447,%22lon%22:-78.576965},{%22lat%22:35.755428,%22lon%22:-78.560486},{%22lat%22:35.
805563,%22lon%22:-78.534393},{%22lat%22:35.793311,%22lon%22:-78.564606},{%22lat%22:35.848987,%22lon%22:-78.539886},{%22lat%22:35.873472,%22lon%2
2:-78.565979},{%22lat%22:35.920196,%22lon%22:-78.590698},{%22lat%22:35.983563,%22lon%22:-78.699188},{%22lat%22:35.991341,%22lon%22:-78.739014},{
%22lat%22:35.806677,%22lon%22:-78.925781},{%22lat%22:35.703032,%22lon%22:-78.821411},{%22lat%22:35.691879,%22lon%22:-78.855743},{%22lat%22:35.69
9686,%22lon%22:-78.896942},{%22lat%22:35.719758,%22lon%22:-78.929901},{%22lat%22:35.665107,%22lon%22:-78.828278},{%22lat%22:35.665107,%22lon%22:
-78.766479},{%22lat%22:35.681841,%22lon%22:-78.740387},{%22lat%22:35.652833,%22lon%22:-78.739014},{%22lat%22:35.658412,%22lon%22:-78.692322},{%2
2lat%22:35.670685,%22lon%22:-78.627777},{%22lat%22:35.667338,%22lon%22:-78.660736},{%22lat%22:35.933541,%22lon%22:-78.874969},{%22lat%22:35.9813
4,%22lon%22:-78.916168}],%22costing%22:%22auto%22,%22units%22:%22mi%22}&api_key= HTTP/1.1
2017/10/24 20:41:07.130436 [INFO] Got Loki Request 0
2017/10/24 20:41:07.131351 [ANALYTICS] locations_count::120
2017/10/24 20:41:07.131413 [ANALYTICS] costing_type::auto
2017/10/24 20:41:07.242126 [ANALYTICS] max_location_distance::105.229729km
2017/10/24 20:41:07.246591 [INFO] Got Thor Request 0
2017/10/24 20:41:07.263522 [ANALYTICS] travel_mode::0
2017/10/24 20:41:07.263555 [ANALYTICS] matrix_type::many_to_many

// Memory during request processing
$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:41:11 UTC 2017
KiB Mem : 53588628 total, 45343472 free,  5173560 used,  3071596 buff/cache

// Another memory check during processing
$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:41:18 UTC 2017
KiB Mem : 53588628 total, 45181652 free,  5335480 used,  3071496 buff/cache

// Valhalla response sent for Request 0
0 2017/10/24 20:41:21.442310 200 894745

// Memory seconds after processing
$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:41:23 UTC 2017
KiB Mem : 53588628 total, 45479336 free,  5037740 used,  3071552 buff/cache

// Memory 3 minutes later
$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:44:20 UTC 2017
KiB Mem : 53588628 total, 45478944 free,  5037512 used,  3072172 buff/cache
```

As you can see, even after 3 minutes, ~5GB of memory still has not released.

So... what happens when there are simultaneous requests?


Expanding this example to 4 simultaneous requests for the same exact 120 locations...

```
$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:54:34 UTC 2017
KiB Mem : 53588628 total, 50167304 free,   348096 used,  3073228 buff/cache

root@5e6747a16a03:/# valhalla_route_service /conf/valhalla.json 
2017/10/24 20:54:37.097734 [WARN] Tile extract could not be loaded

$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:54:40 UTC 2017
KiB Mem : 53588628 total, 50104680 free,   410148 used,  3073800 buff/cache

0 2017/10/24 20:54:46.013725 GET /many_to_many?json={...}
2017/10/24 20:54:46.014052 [INFO] Got Loki Request 0
2017/10/24 20:54:46.014769 [ANALYTICS] locations_count::120
2017/10/24 20:54:46.014834 [ANALYTICS] costing_type::auto
2017/10/24 20:54:46.121922 [ANALYTICS] max_location_distance::105.229729km
2017/10/24 20:54:46.124715 [INFO] Got Thor Request 0
2017/10/24 20:54:46.141743 [ANALYTICS] travel_mode::0
2017/10/24 20:54:46.141777 [ANALYTICS] matrix_type::many_to_many
0 2017/10/24 20:54:59.662171 200 894745

$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:55:00 UTC 2017
KiB Mem : 53588628 total, 45475680 free,  5038500 used,  3074448 buff/cache

1 2017/10/24 20:55:00.843528 GET /many_to_many?json={...}
2017/10/24 20:55:00.843808 [INFO] Got Loki Request 1
2017/10/24 20:55:00.844360 [ANALYTICS] locations_count::120
2017/10/24 20:55:00.844398 [ANALYTICS] costing_type::auto
2017/10/24 20:55:00.952928 [ANALYTICS] max_location_distance::105.229729km
2017/10/24 20:55:00.954273 [INFO] Got Thor Request 1
2017/10/24 20:55:00.971139 [ANALYTICS] travel_mode::0
2017/10/24 20:55:00.971177 [ANALYTICS] matrix_type::many_to_many

$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:55:04 UTC 2017
KiB Mem : 53588628 total, 40785732 free,  9728336 used,  3074560 buff/cache

2 2017/10/24 20:55:07.844202 GET /many_to_many?json={...}
2017/10/24 20:55:07.844515 [INFO] Got Loki Request 2
2017/10/24 20:55:07.845075 [ANALYTICS] locations_count::120
2017/10/24 20:55:07.845131 [ANALYTICS] costing_type::auto
2017/10/24 20:55:07.961948 [ANALYTICS] max_location_distance::105.229729km
2017/10/24 20:55:07.963314 [INFO] Got Thor Request 2
2017/10/24 20:55:07.981068 [ANALYTICS] travel_mode::0
2017/10/24 20:55:07.981111 [ANALYTICS] matrix_type::many_to_many

$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:55:08 UTC 2017
KiB Mem : 53588628 total, 36576392 free, 13937680 used,  3074556 buff/cache

3 2017/10/24 20:55:08.724767 GET /many_to_many?json={...}
2017/10/24 20:55:08.725895 [INFO] Got Loki Request 3
2017/10/24 20:55:08.726450 [ANALYTICS] locations_count::120
2017/10/24 20:55:08.727195 [ANALYTICS] costing_type::auto
2017/10/24 20:55:08.901935 [ANALYTICS] max_location_distance::105.229729km
2017/10/24 20:55:08.905402 [INFO] Got Thor Request 3
2017/10/24 20:55:08.958414 [ANALYTICS] travel_mode::0
2017/10/24 20:55:08.958451 [ANALYTICS] matrix_type::many_to_many

$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:55:11 UTC 2017
KiB Mem : 53588628 total, 31347376 free, 19166728 used,  3074524 buff/cache

1 2017/10/24 20:55:18.589269 200 894745
3 2017/10/24 20:55:23.687444 200 894745
2 2017/10/24 20:55:24.913313 200 894745

$ date; top -n 1 | grep "KiB Mem"
Tue Oct 24 20:56:50 UTC 2017
KiB Mem : 53588628 total, 31512392 free, 19001728 used,  3074508 buff/cache
```

The above shows that the memory is now holding steady at ~19GB but has not not processed any additional requests in the past minute.

Let me know if I can provide any additional details.

Thanks!

**Comment by dnesbitt61** [comment]
You might try a couple changes to how the DoubleBucketQueue is constructed in SetSources and SetTargets

    source_adjacency_[index].reset(new DoubleBucketQueue(0, current_cost_threshold_,
                                         costing_->UnitSize(), edgecost));

    target_adjacency_[index].reset(new DoubleBucketQueue(0, current_cost_threshold_,
                                             costing_->UnitSize(), edgecost));

You can try limiting the current_cost_threshold_ (divide by 2 or something if it exceeds some value) or change the costing_->UnitSize() to 2 seconds or more. Both of these will reduce memory use by DoubleBucketQueue by cutting the number of buckets (an overflow bucket still exists so everything should still work). I think this is the change that was made in June/July that means that code works but newer code does not (the max cost threshold was increased).

**Comment by wdav** [comment]
Ah, so apparently what I was looking at was a red herring, that's not the source of the sustained memory usage (although memory usage does get very high temporarily).

When I run valhalla_route_service as a single thread, I do not have the sustained memory hold.  When I run as 2, it holds onto ~5GB but goes up to to ~10GB when processing 2 requests and drops back to ~5GB when done.  When I run valhalla_route_service with 3, it bursts up to ~15GB and holds on to ~10GB when done... this continues in this pattern.

I verified the cleanups are being called in the appropriate places... so that took me to prime_server. Do you think this prime_server issue might be the cause of the held memory?:
https://github.com/kevinkreiser/prime_server/issues/62

Still trying to track down where the high memory utilization is occurring, but it does not seem to be directly related to DoubleBucketQueue.

Researching...

**Comment by dnesbitt61** [comment]
Are you using the tar'd file (uses memory mapping rather than having each process read tiles into its own cache)? If using individual tile files are you using a shared cache? We recommend using the tar file. Also, did you try either of the changes to CostMatrix to lessen the size of the DoubleBucketQueue(s)?

**Comment by wdav** [comment]
Correct, I'm using the tar file. I did and only noticed a few hundred MB difference max, and it was correctly cleaned up, as you said.

**Comment by xydinesh** [comment]
Do you know if memory issues is fixed in version 2.4.1 ? Looks like it is fixed. Tested this morning and with 16 concurrency, it maxed at 27GB and with 8 concurrency maxed at 14GB for the same test using  m4.4xlarge with colorado.osm.pbf from geofabric.

**Comment by xydinesh** [comment]
@wdav I can't get valhalla/docker:source-1.2.0 working. I'm getting a segfault when building tiles

```
root@5fe0e5394f7b:/test# valhalla_build_tiles -c valhalla.json colorado.osm.pbf
2017/11/22 17:42:01.561038 [INFO] Parsing files: colorado.osm.pbf
2017/11/22 17:42:01.561141 [INFO] Parsing ways...
Segmentation fault (core dumped)
```
It doesn't happend with valhalla/docker:source-1.3.4 though. Didn't you run into issue like above with 1.2.0 image ?

**Comment by wdav** [comment]
@xydinesh I haven't had a chance to verify your results with 2.4.1 but that does sound promising, thanks for the update.

As far as the segfault when building the tiles, yes, you'd have to find the correct historical osm file that doesn't segfault, most current ones do fail iirc. I don't remember now what was fixed but that segfault was addressed shortly after 1.2.0.

**Comment by ecotner** [comment]
Has there been any resolution/update on this? I'm currently using the matrix service and have been running into memory leaks that only become apparent after running several hundred matrix requests. Even after a long time (~30 minutes), the memory is still not reclaimed and I have to kill the process. The size of these matrices are roughly 100x100. I'm using the version of Valhalla installed with `sudo apt-get install -y valhalla-bin` rather than docker.

**Comment by nilsnolde** [comment]
should be solved now
